### ISSUE TITLE
[Bug]: error when running LaunchServer.sh 运行LaunchServer.sh报错。

### ISSUE THREAD

**Issue by CosmosYou** [Rad586/Forget-Me-Not#99]
### Descripiton 简述

**I want to create a server. But here is an error；**
[04:25:12] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: Class net.minecraft.class_1799 does not have member field 'java.text.NumberFormat FORMAT'
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:482) ~[fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.0.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:0.11.2]
**Caused by: java.lang.NoSuchFieldError: Class net.minecraft.class_1799 does not have member field 'java.text.NumberFormat FORMAT'**
        at net.minecraft.class_1799.<clinit>(class_1799.java:126) ~[server-intermediary.jar:?]
        at net.minecraft.class_1761.<init>(class_1761.java:114) ~[server-intermediary.jar:?]
        at net.minecraft.class_1761$1.<init>(class_1761.java:15) ~[server-intermediary.jar:?]
        at net.minecraft.class_1761.<clinit>(class_1761.java:15) ~[server-intermediary.jar:?]
        at net.minecraft.class_1792.<init>(class_1792.java:94) ~[server-intermediary.jar:?]
        at net.minecraft.class_1739.<init>(class_1739.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_1802.<clinit>(class_1802.java:21) ~[server-intermediary.jar:?]
        at net.minecraft.class_1792.method_7867(class_1792.java:74) ~[server-intermediary.jar:?]
        at net.minecraft.class_2248.method_8389(class_2248.java:554) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41583(class_7143.java:60) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143$class_7144.method_41581(class_7143.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_7143.method_41579(class_7143.java:199) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_44104(class_5458.java:98) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:105) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:986) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:104) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:326) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:50) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:98) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.0.jar:?]
        ... 4 more

### Steps to reproduce. 复现问题的步骤

step1: Download FMN2.9.0hf server.zip and  FMN2.9.0hf.zip
step2: Upload the files in FMN2.9.0hf server.zip to my linux server, copy mods downloaded to  mods file.
step3: Donwload  curl -OJ https://meta.fabricmc.net/v2/versions/loader/1.19.2/0.16.0/0.11.2/server/jar, edit its name (I try many versions but it still go wrong )
step4: run LaunchServer.sh

**Comment by Rad586** [comment]
试试用 ATLauncher 启动这个新的服务端。不用单独下载模组了。
Try using ATLauncher to launch this serverpack. You dont have to separately install mods.

**Comment by Rad586** [comment]
试试用 ATLauncher 启动这个新的服务端。不用单独下载模组了。
Try using ATLauncher to launch this serverpack. You dont have to separately install mods.
https://www.curseforge.com/minecraft/modpacks/forget-me-not/files/5790739/additional-files

**Comment by Epsilonkoishi** [comment]
> 试试用 ATLauncher 启动这个新的服务端。不用单独下载模组了。尝试使用 ATLauncher 启动此 serverpack。您不必单独安装 Mod。 https://www.curseforge.com/minecraft/modpacks/forget-me-not/files/5790739/additional-files

请问除了用ATLauncher外没有其他解决办法了吗

**Comment by Epsilonkoishi** [comment]
> > 试试用 ATLauncher 启动这个新的服务端。不用单独下载模组了。尝试使用 ATLauncher 启动此 serverpack。您不必单独安装 Mod。https://www.curseforge.com/minecraft/modpacks/forget-me-not/files/5790739/additional-files
> 
> 请问除了用ATLauncher外没有其他解决办法了吗

我在删除staker这个模组后可以正常启动服务器了

**Comment by Rad586** [comment]
> > 试试用 ATLauncher 启动这个新的服务端。不用单独下载模组了。尝试使用 ATLauncher 启动此 serverpack。您不必单独安装 Mod。 https://www.curseforge.com/minecraft/modpacks/forget-me-not/files/5790739/additional-files
> 
> 请问除了用ATLauncher外没有其他解决办法了吗

应该有，但我不知道。ATLauncher 是我测试服务端时用的，我能保证有效的只有这个方法。
There should be another way, which I don't know. ATLauncher is the launcher I used to test the serverpack, all I can do is to make sure it works in this specific case.
